include @builddir@/mk/defs.mk

LIB=	repo-binary
SRCS=	binary.c \
	common.c \
	fetch.c \
	init.c \
	query.c \
	update.c

LOCAL_CFLAGS=	-I$(prefix)/include \
		-I$(top_srcdir)/libpkg \
		-I$(top_srcdir)

include $(MK)/pic-lib.mk
